AtCoder-NoviSteps/AtCoderNoviSteps

- pnpm-lock.yaml
> 🔧 Update packages (#177)

- CONTRIBUTING.md
> :books: Update CONTRIBUTING (#182)

- compose.yaml
> :boom: Fixed DB version for container (#265)

- src/lib/components/Footer.svelte
> :art: Fix layout in footer (#213)

- README.md
> ✨ Add 💚 AtCoder Clans Sponsor (#292)

- src/lib/services/task_results.ts
- src/lib/types/tasktag.ts
- src/routes/problems/+page.server.ts
/problems?tagIds=3
/problems?tagIds=3,2
で検索できます。複数指定した場合はAND条件です。
> add tag filter for problems(#237)

- src/lib/components/TaskList.svelte
> :art: Fix format for progress bar (#337)

- src/lib/components/TaskForm.svelte
- src/lib/components/TaskList.svelte
- src/lib/components/TaskListForEdit.svelte
- src/lib/services/problemsApiService.ts
- src/lib/types/task.ts
- src/lib/utils/newline.ts
- src/routes/(admin)/tasks/+page.server.ts
- src/routes/(admin)/tasks/+page.svelte
- src/routes/(admin)/tasks/[task_id]/+page.server.ts
- src/routes/(admin)/tasks/[task_id]/+page.svelte
- src/routes/problems/+page.server.ts
- src/routes/problems/+page.svelte
- src/routes/users/[username]/+page.server.ts
・Admin権限でログインをしたとき、Problems/ページから、task/editの画面に遷移できるよう修正
　「編集」ボタンの表示非表示の制御
　「編集」ボタンから遷移するページを作成（登録はまだできない）
・Admin権限でログインをしたとき、tasks/ページを開くと、未登録のタスク一覧（コンテスト毎に登録を想定）を表示できるよう修正
（Problems APIから直接取得のままの状態。taskテーブルのフラグ作成をしてアクセスを減らす対応はしていない）
　ProblemsAPIからのJsonデータ取得
　コンテスト毎の未登録tasksを表示するページを作成
> #163 tasks #114 tags #81 import 画面のみ追加

- src/lib/components/TaskForm.svelte
- src/lib/types/task.ts
- src/routes/(admin)/tasks/+page.server.ts
> update task #114

- .prettierignore
- package.json
- pnpm-lock.yaml
- prisma/ERD.md
- prisma/schema.prisma
Resolve #352 
こんな感じでERDを作れます。
https://github.com/AtCoder-NoviSteps/AtCoderNoviSteps/blob/%23352/prisma/ERD.md
コマンドはこれです
`npx prisma generate`
インストールは
`pnpm install prisma-erd-generator @mermaid-js/mermaid-cli`
> prisma setting to generate ER figure

- LICENSE
> :books: Update LICENSE (#435)

- src/routes/problems/+page.svelte
> ✨ Show　pending tasks for admin only (#405)

- src/lib/components/TagForm.svelte
- src/lib/components/TagListForEdit.svelte
- src/lib/services/tags.ts
- src/lib/services/task_tags.ts
- src/lib/types/tag.ts
- src/routes/(admin)/tags/+page.server.ts
- src/routes/(admin)/tags/+page.svelte
- src/routes/(admin)/tags/[tag_id]/+page.server.ts
- src/routes/(admin)/tags/[tag_id]/+page.svelte
Refs #114 
以下のページを準備。
tags/[tags_id]のPOST処理（tagのupdate）未実装
/tagsページのソート順は未実装（何順がいいかな？）
tags/ ・・・タグ一覧を表示し、タグ詳細ページに遷移できる。
tags/[tag_id] ・・・タグ詳細ページ。タグを一つ一つ変更できるページ、全体的な表示・非表示や、タグの名称を変更できる（tagテーブルのエントリの作成）
> add tag edit view

- src/lib/components/TabItemWrapper.svelte
- src/lib/components/TaskGradeList.svelte
- src/routes/problems/+page.svelte
> :art: Add tabs to problems page (#463)

- .devcontainer/devcontainer.json
- package.json
- pnpm-lock.yaml
- tsconfig.json
> :bug: Fix build error (#474)

- src/lib/components/HeadingOne.svelte
- src/routes/(admin)/tags/+page.svelte
- src/routes/(admin)/tasks/+page.svelte
- src/routes/(admin)/tasks/[task_id]/+page.svelte
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- src/routes/problems/+page.svelte
- src/routes/users/[username]/+page.svelte
> :art: Fix h1 font weight (#476)

- src/routes/(auth)/login/+page.server.ts
- src/routes/(auth)/signup/+page.server.ts
> :bug: Fix breaking change (#495)

- src/lib/constants/product-info.ts
- src/routes/+page.svelte
- tests/signin.test.ts
- tests/toppage.test.ts
> :books: Update product catch phrase (#28)

- src/lib/components/Footer.svelte
- src/lib/components/Header.svelte
- src/lib/constants/product-info.ts
- src/routes/+page.svelte
> :books: Update docs in home page (#538)

- src/lib/constants/external-links.ts
- src/lib/constants/urls.ts
> ✨ Add links for online judges (#540)

- src/lib/components/FormWrapper.svelte
- src/lib/components/UserAccountDeletionForm.svelte
- src/lib/components/WarningMessageOnDeletingAccount.svelte
> ✨ Show message before deleting account (#544)

- src/lib/constants/http-response-status-codes.ts
- src/routes/(auth)/login/+page.server.ts
- src/routes/+page.svelte
> :art: Visible home regardless of login status (#556)

- README.md
- src/lib/constants/product-info.ts
- src/routes/+page.svelte
> :books: Update descriptions (#558)

- src/lib/components/TaskGradeList.svelte
- src/lib/components/TaskList.svelte
- src/lib/utils/task.ts
- src/routes/problems/+page.svelte
> :art: Fix colors (#561)

- src/lib/utils/task.ts
- src/routes/problems/[slug]/+page.svelte
> :books: Fix typo (#563)

- src/lib/components/TaskList.svelte
> :art: Resize table height in problems page (#565)

- tailwind.config.cjs
> :art: Change base colors from red to green (#567)

- src/lib/components/TaskList.svelte
- src/lib/services/submission_status.ts
- src/routes/problems/[slug]/+page.svelte
- tailwind.config.cjs
> :art: Add background colors to problems page (#572)

- src/lib/components/Header.svelte
- src/lib/constants/navbar-links.ts
- src/routes/(admin)/tags/+page.svelte
- src/routes/(admin)/tasks/+page.svelte
- src/routes/(admin)/tasks/[task_id]/+page.svelte
- src/routes/about/+page.svelte
- src/routes/problems/+page.svelte
- src/routes/problems/[slug]/+page.svelte
- src/test/example.test.ts
> :books: Change from English to Japanese in nav and header (#575)

- src/lib/components/TagForm.svelte
- src/lib/components/TagListForEdit.svelte
- src/lib/components/TaskList.svelte
- src/lib/components/TaskListForEdit.svelte
- src/lib/components/TaskListSorted.svelte
> :art: Fix bg color in table (#578)

- src/app.d.ts
- src/hooks.server.ts
- src/lib/components/Header.svelte
- src/routes/+layout.server.ts
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/users/edit/+page.svelte
> :art: Show sign up / login and logout in navbar (#590)

- src/routes/problems/+page.server.ts
> ♻️ Enable to view problems page without login (#588)

- prisma/submission_statuses.ts
- src/lib/services/task_results.ts
- src/routes/problems/[slug]/+page.server.ts
> :bug: Change answer from AC, AC with editiorial and Trying to untried (#571)

- src/lib/components/TaskList.svelte
- src/lib/components/ThermometerProgressBar.svelte
- src/lib/types/submission.ts
> :art: Show multiple colors progress bar in problems page (#589)

- src/lib/utils/contest.ts
- src/routes/problems/+page.svelte
> :bug: Sort by contest and task ids (#300)

- README.md
- src/routes/+page.svelte
> :art: Add demo (#619)

- src/routes/about/+page.svelte
> :books: Add privacy policy (#623)

- README.md
- src/lib/utils/contest.ts
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- tailwind.config.cjs
> :pencil2: Fix descriptions and colors (#636)

- src/lib/services/tasks.ts
- src/routes/(admin)/tasks/+page.server.ts
> :bug: Not create registered tasks and fixed contest filtering (#643)

- src/lib/constants/external-links.ts
- src/lib/utils/contest.ts
> :book: Fix contest and link name (#650)

- README.md
- src/routes/about/+page.svelte
> :books: Fix links (#661)

- README.md
- src/lib/components/TaskList.svelte
- src/lib/components/TaskListSorted.svelte
- src/lib/services/submission_status.ts
- src/lib/services/task_results.ts
- src/lib/types/task.ts
- src/routes/problems/[slug]/+page.svelte
> :books: Improve alt text in submission status (#652)

- src/lib/utils/contest.ts
> ✨ Import APG4bPython (#669)

- README.md
> ✨ Add 🌐 Domain Supporter (#673)

- pnpm-lock.yaml
> 🔧 Update pnpm-lock.yaml (#683)

- package.json
- pnpm-lock.yaml
> 🔧 Revert pnpm from 9 to 8 (#709)

- prisma/migrations/20240420112403_add_on_delete_attr_to_workbook_task/migration.sql
- prisma/schema.prisma
> ✨ Add onDelete attr to WorkBookTask table (#696)

- src/routes/problems/+page.svelte
- src/routes/users/edit/+page.svelte
> :art: Try to fix tab styles (#727)

- prisma/ERD.md
- prisma/migrations/20240428120340_add_description_to_workbook/migration.sql
- prisma/schema.prisma
- src/lib/components/WorkBooks/WorkBookInputFields.svelte
- src/lib/services/workbooks.ts
- src/lib/types/workbook.ts
- src/lib/zod/schema.ts
- src/routes/workbooks/[slug]/+page.server.ts
- src/routes/workbooks/[slug]/+page.svelte
- src/routes/workbooks/create/+page.svelte
> ✨ Add description to workbooks (#751)

- src/lib/components/WorkBooks/WorkBookList.svelte
- src/lib/services/workbooks.ts
- src/routes/workbooks/+page.server.ts
- src/routes/workbooks/+page.svelte
> ✨ Enable to delete workbooks (#699)

- src/routes/workbooks/[slug]/+page.svelte
> :books: Add links (#791)

- src/lib/services/task_results.ts
> :bug: Hide answers when user is not logged in (#660)

- src/lib/components/AuthForm.svelte
- src/lib/components/MessageHelperWrapper.svelte
> :bug: Fix bug that caused form to be submitted when show / hide password button is clicked (#818)

- src/lib/components/TaskList.svelte
> :art: Improve UI (#871)

- .husky/pre-commit
- package.json
> 🔧 Migrate husky from v8 to v9 (#883)

- src/lib/components/Header.svelte
> :art: Display message before logout (#642)

- pnpm-lock.yaml
> :bug: Fix broken pnpm-lock.yaml (#915)

- pnpm-lock.yaml
> :bug: Fix broken pnpm-lock.yaml (#964)

- src/routes/about/+page.svelte
> :art: Fix layout (#1127)

- src/routes/workbooks/[slug]/+page.svelte
> :bug: Fix conflict (#1135)

- src/routes/workbooks/[slug]/+page.svelte
- src/routes/workbooks/edit/[slug]/+page.svelte
> :art: Improve style for breadcrumb  (#1155)
